import type { Scenario } from "./types";

export const theSidecarWithTheMicrophone: Scenario = {
  id: "the-sidecar-with-the-microphone",
  title: "The Sidecar With The Microphone",
  subtitle: "every metric on the user-profile-service dashboard is either stuck at zero or clearly not what it claims to be",
  difficulty: "medium",
  type: "fix",
  topic: "observability",
  timeMinutes: 15,
  tags: ["prometheus", "service-mesh", "scrape-config"],
  briefing: `user-profile-service's Grafana dashboard has looked wrong since the day
the team adopted the shared service mesh sidecar - request counts are
suspiciously low, memory usage graphs look flat and generic, and none of
the application-specific business metrics the team instrumented (like
"profile_completeness_score") show up at all. Nobody's touched the
application's own metrics code since well before the sidecar rollout.`,
  constraints: [
    "The application container itself is confirmed healthy and, via `kubectl exec` + `curl localhost:8080/metrics`, is confirmed to still be emitting all its normal metrics correctly on its own port.",
  ],
  world: {
    resources: [
      {
        apiVersion: "apps/v1",
        kind: "Deployment",
        metadata: { name: "user-profile-service", namespace: "profiles", labels: { app: "user-profile-service" } },
        spec: {
          replicas: 3,
          template: {
            spec: {
              containers: [
                { name: "user-profile-service", ports: [{ name: "http-metrics", containerPort: 8080 }] },
                { name: "mesh-sidecar", ports: [{ name: "http-metrics", containerPort: 15090 }] },
              ],
            },
          },
        },
        status: { readyReplicas: 3, updatedReplicas: 3, availableReplicas: 3 },
        age: "3mo",
      },
      {
        apiVersion: "monitoring.coreos.com/v1",
        kind: "ServiceMonitor",
        metadata: { name: "user-profile-service", namespace: "profiles" },
        spec: {
          selector: { matchLabels: { app: "user-profile-service" } },
          endpoints: [{ port: "http-metrics", path: "/metrics", interval: "30s" }],
        },
        age: "3mo",
      },
      {
        apiVersion: "v1",
        kind: "ConfigMap",
        metadata: { name: "servicemonitor-port-notes", namespace: "profiles" },
        spec: {
          data: {
            "notes.md":
              "Both containers in this pod expose a port literally *named*\n`http-metrics` - the application container on 8080, and the mesh\nsidecar's own Envoy stats endpoint on 15090. A ServiceMonitor endpoint\nselects a target port *by name* across the whole pod, and when multiple\ncontainers expose a port with the same name, Kubernetes Service port\nresolution and Prometheus Operator's target generation use whichever one\nthe underlying Service's `spec.ports` entry actually maps to - in this\ncase the Service was generated by the mesh's sidecar injection tooling\nand its `http-metrics` port entry points at 15090 (the sidecar), not\n8080 (the application).\n",
          },
        },
        age: "3mo",
      },
    ],
  },
  hints: [
    "`kubectl exec` into the pod and `curl localhost:8080/metrics` directly - the application's own metrics are confirmed fine at the source. So what is Prometheus actually scraping instead?",
    "`kubectl get configmap servicemonitor-port-notes -n profiles -o yaml` - both containers in this pod expose a port with the exact same name. Which one does the generated Service's `http-metrics` port actually forward to?",
    "A ServiceMonitor selects a port *by name*, not by container - if two containers in the same pod happen to share a port name, whichever one the Service's port mapping resolves to is the one Prometheus ends up scraping, silently, with no error.",
  ],
  options: [
    {
      id: "servicemonitor-scraping-sidecar-not-app",
      label:
        "Both the application container and the mesh sidecar expose a port named `http-metrics` (8080 and 15090 respectively), and the Service generated by the mesh's sidecar-injection tooling maps that port name to the sidecar's 15090, not the app's 8080 - so the ServiceMonitor, which selects by port name, has been scraping the sidecar's generic Envoy stats endpoint the entire time instead of the application's own metrics, which explains both the generic-looking data and the total absence of any application-specific business metrics.",
      explanation:
        "`servicemonitor-port-notes` confirms both containers share the literal port name `http-metrics`, and that the generated Service's port mapping for that name points at the sidecar's 15090, not the application's 8080. The ServiceMonitor's endpoint selects `port: http-metrics` by name, with no way to distinguish which container that name actually belongs to once the Service itself resolves it - so every scrape has been hitting the sidecar's own stats, which happens to include some real-looking-but-generic numbers (like a low, mesh-level request count) while never touching any of the application's actual instrumented metrics, consistent with confirming the app's own `/metrics` endpoint is fine when checked directly.",
    },
    {
      id: "app-metrics-broken-by-sidecar-injection",
      label: "The mesh sidecar injection process broke the application's metrics library configuration.",
      explanation:
        "The application container is directly confirmed, via `kubectl exec` and a direct `curl` to its own port, to still be emitting all its normal metrics correctly - the application's own instrumentation and configuration are unaffected. The problem is entirely about what Prometheus is scraping, not what the application produces.",
    },
    {
      id: "prometheus-scrape-target-down",
      label: "Prometheus's scrape target for user-profile-service is marked down / unreachable.",
      explanation:
        "There's no indication the scrape target itself is failing or unreachable - quite the opposite, it's succeeding and returning real (if generic, low, and business-metric-free) data every time, which is consistent with successfully scraping the wrong endpoint rather than failing to reach any endpoint at all.",
    },
    {
      id: "dashboard-queries-outdated-metric-names",
      label: "The Grafana dashboard's queries use outdated metric names that no longer match what the app exports.",
      explanation:
        "Nobody has touched the application's own metrics code or naming since before the sidecar rollout, and the app's own `/metrics` endpoint is confirmed to still emit everything as expected - the dashboard's queries aren't stale, they're just never seeing the application's metrics at all because Prometheus isn't scraping that endpoint in the first place.",
    },
  ],
  correctOptionId: "servicemonitor-scraping-sidecar-not-app",
  resolution: `A direct \`kubectl exec\` and \`curl localhost:8080/metrics\` confirms the
application container's own metrics endpoint is completely healthy and
unaffected. \`servicemonitor-port-notes\` explains where the dashboard data
is actually coming from instead: both the application container (port
8080) and the mesh sidecar (port 15090) expose a port with the exact same
name, \`http-metrics\`. The ServiceMonitor's endpoint selects \`port:
http-metrics\` purely by name, and name resolution happens through the
generated Kubernetes Service's own port mapping - which, because it was
generated by the mesh's automatic sidecar-injection tooling, maps
\`http-metrics\` to the sidecar's port 15090, not the application's 8080.
Every scrape has been quietly landing on the sidecar's generic Envoy
stats endpoint the entire time - close enough to look like *some*
real metrics (a request count, memory-adjacent numbers), but with none of
the application's actual instrumented business metrics anywhere in it,
because the application's port was never being scraped at all.

This is an easy trap once a service mesh sidecar is added: both
containers' operators tend to use conventional, identical port names
(\`http-metrics\`, \`metrics\`, \`http\`) independently, and Kubernetes has no
built-in mechanism to flag the collision - whichever one the Service
happens to route that name to silently wins.

The fix is giving each container's metrics port a distinct name, and
pointing the ServiceMonitor explicitly at the application's:

\`\`\`yaml
# app container port
ports: [{ name: app-metrics, containerPort: 8080 }]

# ServiceMonitor
spec:
  endpoints:
    - port: app-metrics
      path: /metrics
\`\`\`

Once the ServiceMonitor targets a uniquely-named port that only the
application container exposes, Prometheus starts scraping the real
application metrics, and \`profile_completeness_score\` - and every other
business metric the team actually instrumented - starts showing up on
the dashboard for the first time since the sidecar rollout.`,
};
